const $ = (s) => document.querySelector(s);
const esc = (v) => String(v ?? '—').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const LOCALES = { en:'en-US', es:'es-CL', pt:'pt-BR', fr:'fr-FR', de:'de-DE' };
let state = { models: [], active: null, selected: null, help: {}, detail: null, refreshInFlight: false };
function uiLocale() { return LOCALES[localStorage.getItem('strata_lang') || 'en'] || LOCALES.en; }
function tok() { return localStorage.getItem('strata_tok') || ''; }
function fmt(v, digits = 0) { if (v === null || v === undefined || v === '') return '—'; const n = Number(v); return Number.isFinite(n) ? n.toLocaleString(uiLocale(), { maximumFractionDigits: digits }) : esc(v); }
function mem(v) { if (v === null || v === undefined || v === '') return '—'; const n = Number(v); return Number.isFinite(n) ? `${(n / 1024).toLocaleString(uiLocale(), { maximumFractionDigits: 1 })} GiB` : esc(v); }
function flash(message, error = false) { const el = $('#status'); if (el) { el.textContent = message; el.className = 'status on' + (error ? ' err' : ''); clearTimeout(flash.timer); flash.timer = setTimeout(() => { el.className = 'status'; }, 4200); } const log = $('#log'); if (log) log.textContent = `${new Date().toLocaleTimeString()}  ${message}\n${log.textContent}`.slice(0, 8000); }
async function api(path, body) { const r = await fetch(path, { method: body === undefined ? 'GET' : 'POST', headers: { 'X-Strata-Token': tok(), ...(body === undefined ? {} : {'Content-Type':'application/json'}) }, body: body === undefined ? undefined : JSON.stringify(body) }); const d = await r.json().catch(() => ({})); if (!r.ok) throw new Error(d?.error?.message || `${r.status} ${r.statusText}`); return d; }
const VALID_TABS = new Set(['models','perf','traces','log','connection','tunnel','update','add','prefs','params','opt']);
function setTab(name, replace = true) {
  if (!VALID_TABS.has(name)) name = 'models';
  if (replace) history.replaceState(null, '', `#${name}`);
  const target=document.querySelector(`.tab[data-v="${name}"]`);
  document.querySelectorAll('.nav-group').forEach(g=>{g.open=!!target && g.contains(target);});
  document.querySelectorAll('.tab,.view').forEach(el => el.classList.toggle('on', el.dataset.v === name));
  document.querySelectorAll('.tab').forEach(el => { el.setAttribute('aria-selected', String(el.dataset.v === name)); el.setAttribute('aria-controls', `view-${el.dataset.v}`); });
  document.querySelectorAll('.view').forEach(el => { el.id = `view-${el.dataset.v}`; el.setAttribute('role','tabpanel'); el.setAttribute('aria-hidden', String(el.dataset.v !== name)); }); if (name === 'perf') loadPerformance(); if (name === 'traces') loadTraces(); if (name === 'connection') loadConnection(); if (name === 'prefs') { applyPreferences(); renderQuickHelp(); } if (name === 'params') loadParams(); if (name === 'update') loadUpdate(false); if (name === 'tunnel') loadTunnel();
}
function renderChips() { $('#chips').replaceChildren(...state.models.map(m => { const b = document.createElement('button'); b.className = `sw${m.active?' on':''}${m.running?' run':''}`; b.innerHTML = `<i class="dot"></i><span>${esc(m.label)}</span><span class="p">:${m.port}</span>`; b.onclick = () => selectModel(m.id); return b; })); }
function renderModels() { const body = $('#tblModels tbody'); body.replaceChildren(...state.models.map(m => { const tr = document.createElement('tr'); if (m.active) tr.className = 'act'; const st = m.active ? 'a' : m.running ? 'r' : 'o'; tr.innerHTML = `<td><span class="nm">${esc(m.label)}</span><br><span class="id">${esc(m.id)}</span></td><td class="n"><span class="st ${st}">${m.active ? t('st_active') : m.running ? t('st_running') : t('st_stopped')}</span></td><td class="n">:${m.port}</td><td class="n">${fmt(m.tok_s,1)}</td><td class="n">${fmt(m.context)}</td><td class="n">${esc(m.kv || '—')}</td><td class="n">${fmt(m.vram_free_mib)} MiB</td><td class="n">${esc(m.engine || '—')}</td><td class="n"><div class="acts"><button class="mini" data-a="use">${t('a_use')}</button><button class="mini" data-a="params">${t('a_params')}</button><button class="mini" data-a="unload">${t('a_unload')}</button><button class="mini dz" data-a="remove">${t('a_remove')}</button></div></td>`; tr.querySelectorAll('button').forEach(b => b.onclick = () => modelAction(b.dataset.a, m.id)); return tr; })); }
function updateGauges(d) { const gpu = d.gpu || {}, ram = d.ram || {}; const gp = gpu.total_mib ? gpu.used_mib / gpu.total_mib * 100 : 0, rp = ram.total_mib ? ram.used_mib / ram.total_mib * 100 : 0; for (const [bar, text, pct, value] of [['#gVram','#gVramT',gp,`${mem(gpu.used_mib)} / ${mem(gpu.total_mib)}`],['#gRam','#gRamT',rp,`${mem(ram.used_mib)} / ${mem(ram.total_mib)}`],['#gUtil','#gUtilT',Number(gpu.util)||0,`${fmt(gpu.util)}%`]]) { const b=$(bar); if(b){b.style.width=`${Math.min(100,pct)}%`;b.className=pct>90?'max':pct>75?'hi':'';} const x=$(text); if(x)x.textContent=value; } $('#gEnv').textContent = gpu.temp_c ? `${gpu.temp_c}°C · ${fmt(gpu.power_w,1)}W` : '—'; }
function updateOverview(d) {
  const m = state.models.find(x => x.active) || state.models.find(x => x.id === state.active);
  const gpu = d.gpu || {};
  $('#ovActive').textContent = m?.label || state.active || '—';
  $('#ovActivePort').textContent = m ? `:${m.port} · ${m.running ? t('st_running') : t('st_stopped')}` : '—';
  $('#ovContext').textContent = fmt(m?.context);
  $('#ovKv').textContent = m?.kv ? `KV ${m.kv}` : 'KV —';
  $('#ovLoad').textContent = gpu.util == null ? '—' : `${fmt(gpu.util)}%`;
  $('#ovGpuTemp').textContent = gpu.temp_c == null ? 'GPU —' : `${fmt(gpu.temp_c)}°C · ${fmt(gpu.used_mib)} MiB`;
  $('#ovModels').textContent = fmt(state.models.length);
}
async function refresh() {
  if (state.refreshInFlight || document.visibilityState === 'hidden') return;
  state.refreshInFlight = true;
  try { const d = await api('/api/status'); state.models=d.models||[]; state.active=d.active_model; updateGauges(d); updateOverview(d); renderChips(); renderModels(); $('#liveTag').textContent = `${t('active_short')} · ${state.active || '—'}`; const a=state.models.find(m=>m.active); $('#rateTag').textContent = a?.tok_s ? `${fmt(a.tok_s,1)} tok/s` : '—'; }
  catch (e) { flash(`status: ${e.message}`, true); }
  finally { state.refreshInFlight = false; }
}
async function waitJob(id) { for (let i=0;i<900;i++) { const job=await api(`/api/jobs/${encodeURIComponent(id)}`); if(job.status==='succeeded') return job.result||{}; if(job.status==='failed') throw new Error(job.error||'job failed'); if(job.status==='cancelled') throw new Error('job cancelled'); await new Promise(r=>setTimeout(r,1000)); } throw new Error('job timeout'); }
async function selectModel(id) { try { flash(`cambiando a ${id}; la carga puede tardar varios minutos`); const d=await api('/api/select',{model:id}); if(d.job_id) await waitJob(d.job_id); flash(`modelo activo: ${id}`); await refresh(); } catch(e){flash(e.message,true);} }
async function modelAction(action,id) { try { if(action==='use') return selectModel(id); if(action==='params'){state.selected=id;setTab('params');return;} if(action==='remove'){if(!window.confirm(`Quitar ${id} del catálogo? No se borrarán GGUF ni packs.`))return; await api('/api/remove',{model:id}); flash(`modelo quitado del catálogo: ${id}`); await refresh(); return;} await api(`/api/${action==='unload'?'unload':'stop'}`,{model:id}); flash(`${action==='unload'?'descargado':'detenido'}: ${id}`); await refresh(); } catch(e){flash(e.message,true);} }
function metric(label,value,unit='',kind='') { return `<div class="mt ${kind}"><span>${esc(label)}</span><b>${esc(value)} <small>${esc(unit)}</small></b></div>`; }
async function loadPerformance() { const m=state.models.find(x=>x.id===state.selected)||state.models.find(x=>x.active)||state.models[0]; if(!m)return; try { const seconds=Number($('#histRange')?.value||86400); const [d,h,c]=await Promise.all([api(`/api/detail?model=${encodeURIComponent(m.id)}`),api(`/api/history?model=${encodeURIComponent(m.id)}&since=${Math.floor(Date.now()/1000)-seconds}`),api(`/api/history-compare?model=${encodeURIComponent(m.id)}`)]); state.detail=d; const e=d.engine||{}, l=d.live||{}; $('#perfSrc').textContent=m.id; $('#metrics').innerHTML=[metric('decode',fmt(l.tok_s,1),'tok/s','g'),metric('promedio',fmt(l.tok_s_mean,1),'tok/s'),metric('prefill',fmt(l.prefill_tok_s_mean,1),'tok/s'),metric('VRAM libre',fmt(e.vram_free_mib),'MiB'),metric('expert cache',fmt(e.expert_cache_mib),'MiB'),metric('cola',fmt(l.queued),'requests')].join(''); drawChart(h.rows||[]); $('#tblCmp tbody').innerHTML=(c.setups||[]).map(x=>`<tr><td><code>${esc(JSON.stringify(x.setup||{}))}</code></td><td class="n">${fmt(x.samples)}</td><td class="n">${fmt(x.tok_s_mean_avg,1)}</td><td class="n">${fmt(x.prefill_avg,1)}</td></tr>`).join('') || '<tr><td colspan="4" class="dim">sin muestras todavía</td></tr>'; } catch(e){flash(`performance: ${e.message}`,true);} }
function drawChart(rows) { const c=$('#chart'); if(!c)return; const ctx=c.getContext('2d'), w=c.clientWidth||1200, h=220, ratio=window.devicePixelRatio||1; c.width=w*ratio;c.height=h*ratio;ctx.scale(ratio,ratio);ctx.clearRect(0,0,w,h);const vals=rows.map(x=>Number(x.tok_s_mean||x.tok_s)).filter(Number.isFinite);if(!vals.length){ctx.fillStyle='#657284';ctx.fillText('sin datos históricos',20,30);return;}const max=Math.max(...vals)*1.1,min=Math.min(...vals)*.9;ctx.strokeStyle='#4d8fd6';ctx.lineWidth=2;ctx.beginPath();vals.forEach((v,i)=>{const x=i*(w-20)/(vals.length-1||1)+10,y=h-20-(v-min)/(max-min||1)*(h-40);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();}
const HELP_TABS = ['models','perf','traces','connection','prefs','params','opt','update','tunnel','add','log'];
function applyPreferences() {
  const theme=localStorage.getItem('strata_theme')||'dark', density=localStorage.getItem('strata_density')||'compact', motion=localStorage.getItem('strata_motion')==='1';
  document.documentElement.classList.remove('theme-ink','theme-light','density-comfortable','reduce-motion');
  if(theme!=='dark')document.documentElement.classList.add(`theme-${theme}`); if(density==='comfortable')document.documentElement.classList.add('density-comfortable'); if(motion)document.documentElement.classList.add('reduce-motion');
  if($('#prefTheme'))$('#prefTheme').value=theme; if($('#prefDensity'))$('#prefDensity').value=density; if($('#prefMotion'))$('#prefMotion').checked=motion; if($('#prefReasoning'))$('#prefReasoning').checked=localStorage.getItem('strata_reasoning')!=='0';
}
function renderQuickHelp() { const box=$('#quickHelp'); if(!box)return; box.innerHTML=HELP_TABS.map(k=>`<article><b>${esc(t('tab_'+k))}</b><p>${esc(t('help_'+k))}</p></article>`).join(''); document.querySelectorAll('.tab').forEach(el=>{const k=el.dataset.v;el.title=t('help_'+k)||'';el.setAttribute('aria-label',`${t('tab_'+k)}: ${t('help_'+k)||''}`);}); }
function savePreferences() { localStorage.setItem('strata_theme',$('#prefTheme').value);localStorage.setItem('strata_density',$('#prefDensity').value);localStorage.setItem('strata_motion',$('#prefMotion').checked?'1':'0');localStorage.setItem('strata_reasoning',$('#prefReasoning').checked?'1':'0');applyPreferences();renderQuickHelp();flash(t('prefs_saved')||'Preferencias guardadas'); }
function resetPreferences() { ['strata_theme','strata_density','strata_motion','strata_reasoning'].forEach(k=>localStorage.removeItem(k));applyPreferences();renderQuickHelp();flash(t('prefs_reset_done')||'Preferencias restauradas'); }
async function loadConnection() {
  try {
    const d = await api('/api/connection');
    const isLan = d.mode === 'lan';
    $('#connMode').textContent = isLan ? t('conn_lan_status') : t('conn_local_status');
    $('#connModeNote').textContent = `${d.bind_host}:${d.port} · ${d.auth_remote_required ? 'Bearer token' : 'sin auth'}`;
    $('#connDot').className = `conn-dot${isLan ? ' lan' : ''}`;
    $('#connModeSelect').value = d.mode; $('#connCors').checked = !!d.cors;
    const local = `curl ${d.local_url}/chat/completions -H 'Content-Type: application/json' -H 'Authorization: Bearer <token>'`;
    const lan = d.lan_url ? `curl ${d.lan_url}/chat/completions -H 'Content-Type: application/json' -H 'Authorization: Bearer <token>'` : 'Activa Red local para obtener una URL de red.';
    $('#connUrls').innerHTML = `<div class="conn-url"><span>API local</span><code>${esc(d.local_url)}</code><small class="hint">${esc(local)}</small></div><div class="conn-url"><span>API desde otro PC</span><code>${esc(d.lan_url || 'no expuesta')}</code><small class="hint">${esc(lan)}</small></div><div class="conn-url"><span>Panel</span><code>${esc(d.panel_lan_url || d.panel_local_url)}</code><small class="hint">Header: ${esc(d.auth_header)}</small></div><div class="security-note">${t('conn_security')}<br><b>${t('conn_restart')}</b></div>`;
  } catch(e) { flash(`conexión: ${e.message}`, true); }
}
async function applyConnection() { try { const d=await api('/api/connection',{mode:$('#connModeSelect').value,cors:$('#connCors').checked}); flash(`${d.note}`); await loadConnection(); } catch(e) { flash(`conexión: ${e.message}`,true); } }
function traceStatus(row) { return row.status === 'running' ? t('trace_running') : row.status === 'error' ? t('trace_error') : t('trace_completed'); }
function renderTraceDetail(row) {
  if (!row) { $('#traceDetail').innerHTML = `<div class="trace-empty">${t('trace_select')}</div>`; $('#traceState').textContent='—'; return; }
  $('#traceState').textContent = `${row.status} · ${row.model}`;
  const usage = row.usage || {};
  $('#traceDetail').innerHTML = `<div class="trace-summary"><div><span>modelo</span><b>${esc(row.model)}</b></div><div><span>duración</span><b>${fmt(row.duration_ms,1)} ms</b></div><div><span>tokens</span><b>${fmt(usage.total_tokens)}</b></div><div><span>finish</span><b>${esc(row.finish_reason || '—')}</b></div></div>
    <div class="trace-block"><h3>${t('trace_prompt')}</h3><pre>${esc(row.prompt || '—')}</pre></div>
    <div class="trace-block"><h3>${t('trace_reasoning')}</h3><pre>${localStorage.getItem('strata_reasoning')==='0' ? 'Oculto por preferencia local.' : esc(row.reasoning || 'El modelo no expuso razonamiento en esta request.')}</pre></div>
    <div class="trace-block"><h3>${t('trace_response')}</h3><pre>${esc(row.response || '—')}</pre></div>
    ${row.error ? `<div class="trace-block trace-error-block"><h3>${t('trace_errors')}</h3><pre>${esc(row.error)}</pre></div>` : ''}
    ${row.tool_calls?.length ? `<div class="trace-block"><h3>${t('trace_tools')}</h3><pre>${esc(JSON.stringify(row.tool_calls,null,2))}</pre></div>` : ''}`;
}
async function loadTraces() {
  try {
    const d = await api('/api/traces?limit=50');
    const rows = d.traces || [];
    $('#traceList').innerHTML = rows.length ? rows.map(r => `<button class="trace-row${r.status==='error'?' error':''}" data-trace="${esc(r.id)}"><b>${esc(r.model)}</b><span class="trace-meta">${fmt(r.duration_ms,1)} ms</span><small>${esc(r.path)} · ${new Date((r.started_at||0)*1000).toLocaleTimeString()}</small><span class="trace-status">${traceStatus(r)}${r.reasoning ? ' · reasoning' : ''}${r.response ? ' · response' : ''}</span></button>`).join('') : `<div class="trace-empty">${t('trace_empty')}</div>`;
    document.querySelectorAll('[data-trace]').forEach(b => b.onclick = () => { document.querySelectorAll('.trace-row').forEach(x=>x.classList.remove('on')); b.classList.add('on'); renderTraceDetail(rows.find(x=>x.id===b.dataset.trace)); });
    if (rows[0]) { const first = document.querySelector('[data-trace]'); first?.classList.add('on'); renderTraceDetail(rows[0]); }
  } catch(e) { flash(`trazabilidad: ${e.message}`, true); }
}
async function loadParams() { const id=state.selected||state.active; if(!id)return; $('#pTarget').textContent=id; try { const [help,cfg]=await Promise.all([api('/api/params-help'),api(`/api/config-get?model=${encodeURIComponent(id)}`)]); state.help=help; const values={...(cfg.values||{}),...(cfg.sampling||{})}; $('#pFile').textContent=cfg.file||''; const groups={engine:[],sampling:[],other:[]}; Object.entries(help).forEach(([k,v])=>groups[v.flag==='sampling'?'sampling':v.flag==='config'?'other':'engine'].push([k,v])); $('#pgrid').innerHTML=Object.entries(groups).map(([name,items])=>`<fieldset><legend>${name}</legend>${items.map(([k,v])=>field(k,v,values[k])).join('')}</fieldset>`).join(''); } catch(e){flash(`parámetros: ${e.message}`,true);} }
function field(k,v,value) { const label=`<span title="${esc(v.es||'')}">${esc(k)}${v.restart?' · restart':''}</span>`; if(v.type==='bool')return `<label class="chk">${label}<input id="p_${k}" type="checkbox" ${value?'checked':''}></label>`; if(v.options)return `<label>${label}<select id="p_${k}">${v.options.map(x=>`<option ${String(x)===String(value)?'selected':''}>${esc(x)}</option>`).join('')}</select></label>`; return `<label>${label}<input id="p_${k}" value="${esc(value??'')}" ${v.range?`min="${v.range[0]}" max="${v.range[1]}"`:''}></label>`; }
async function saveParams() { const id=state.selected||state.active;if(!id)return flash('selecciona un modelo primero',true); const body={model:id,sampling:{}}; Object.entries(state.help).forEach(([k,v])=>{const el=$(`#p_${k}`);if(!el)return;let val=v.type==='bool'?el.checked:el.value.trim();if(val==='')return;if(v.flag==='sampling'||['temperature','top_p','top_k','min_p','seed'].includes(k))body.sampling[k]=Number(val);else if(v.type!=='path'&&!Number.isNaN(Number(val)))body[k]=Number(val);else body[k]=val;}); try{const d=await api('/api/config',body);flash(`configuración guardada; requiere reinicio: ${d.file}`);}catch(e){flash(e.message,true);} }
async function runOptimize() { try {const model=state.selected||state.active;const d=await api(`/api/optimize?context=${encodeURIComponent($('#optCtx').value)}&profile=${encodeURIComponent($('#optProfile').value)}&model=${encodeURIComponent(model||'')}`); const rec=d.recommended; $('#optOut').innerHTML=rec?`<div class="callout"><b>${t('opt_reco')}</b> · confianza ${esc(d.confidence||'—')}<br>${esc(rec.why)}<br><span class="hint">VRAM KV: ${fmt(rec.estimates.kv_vram_mib)} MiB · RAM KV: ${fmt(rec.estimates.kv_ram_mib)} MiB · expertos: ${fmt(rec.estimates.expert_budget_mib)} MiB</span><br><code>${esc(JSON.stringify(rec.config))}</code><br><button id="optApply" class="pri">${t('opt_apply')}</button></div><h3>${t('opt_alt')}</h3>${(d.alternatives||[]).map(x=>`<div class="callout"><code>${esc(JSON.stringify(x.config))}</code><br>${esc(x.why)}<br><span class="hint">${esc((x.risks||[]).join(' · ')||'sin riesgos destacados')}</span></div>`).join('')}<p class="hint">${esc(d.note||t('opt_est'))}</p>`:'<div class="callout">No hay combinación viable con la memoria actual.</div>'; $('#optApply')?.addEventListener('click',()=>applyRecommended(rec.config)); }catch(e){flash(`optimizador: ${e.message}`,true);} }
async function runEvaluation() {
  const model=state.selected||state.active;
  if(!model)return flash('selecciona un modelo antes de evaluar',true);
  const btn=$('#evalBtn'); if(btn)btn.disabled=true;
  const status=$('#evalStatus'); if(status){status.hidden=false;status.textContent='Evaluación bloqueando inferencia y preparando candidatos…';}
  try {
    const d=await api('/api/evaluations',{model,context:Number($('#optCtx').value)||200000,profile:$('#optProfile').value||'balanced',runs:Number($('#evalRuns').value)||3,long_prompt_chars:Number($('#evalLongChars').value)||120000});
    const result=await waitJob(d.job_id);
    renderEvaluation(result);
    if(status)status.textContent=`Evaluación completa: ${result.results?.length||0} candidatos medidos.`;
  } catch(e) { if(status){status.hidden=false;status.textContent=`Evaluación: ${e.message}`;} flash(e.message,true); }
  finally { if(btn)btn.disabled=false; }
}
function renderEvaluation(result) {
  const box=$('#evalResults'); if(!box)return;
  box.innerHTML=(result.results||[]).map(row=>{const s=row.score||{},sh=row.short||{},lo=row.long||{};return `<article class="eval-row${row.rank===1?' best':''}"><b>#${row.rank||'—'} · score ${fmt(s.score,2)}</b><small>short ${fmt(sh.decode_tok_s?.mean,2)} tok/s · long ${fmt(lo.decode_tok_s?.mean,2)} tok/s · long p95 ${fmt(lo.latency_ms?.p95,1)} ms · success ${fmt(((sh.success_rate+lo.success_rate)/2*100),1)}%</small><button class="mini pri" data-eval-apply="${esc(row.candidate_index)}">${t('eval_apply')}</button><details><summary>${t('eval_details')}</summary><pre>${esc(JSON.stringify({config:row.config,risks:row.risks,score:row.score},null,2))}</pre></details></article>`;}).join('') || `<div class="trace-empty">${t('eval_empty')}</div>`;
  box.querySelectorAll('[data-eval-apply]').forEach(btn=>btn.onclick=()=>applyEvaluation(result.job_id,Number(btn.dataset.evalApply)));
}
async function applyEvaluation(jobId,candidateIndex){try{const d=await api(`/api/evaluations/${encodeURIComponent(jobId)}/apply`,{candidate_index:candidateIndex});flash(`configuración medida aplicada a ${d.model}; reinicio completado`);await refresh();if(state.selected||state.active)setTab('params');}catch(e){flash(e.message,true);}}
async function loadUpdate(fresh) { try{const d=await api(`/api/update-status${fresh?'?fresh=1':''}`);$('#updKv').innerHTML=[['engine local',d.engine_version],['commit local',d.local_commit],['commit remoto',d.remote_commit],['atrás',d.behind],['estado',d.error|| (d.update_available?t('upd_available'):t('upd_current'))]].map(x=>`<div><span>${esc(x[0])}</span><b>${esc(x[1]??'—')}</b></div>`).join('');$('#updBtn').disabled=!d.update_available;$('#updNote').textContent=d.local_dirty?'Hay cambios locales; la actualización los conserva mediante stash/merge.':'La verificación no modifica el código.';}catch(e){flash(`actualización: ${e.message}`,true);} }
async function loadTunnel(){try{const d=await api('/api/tunnel-status');$('#tunKv').innerHTML=[['estado',d.running?t('tun_on'):t('tun_off')],['URL',d.url||'—'],['API key configurada',d.api_key_set?'sí':'no']].map(x=>`<div><span>${x[0]}</span><b>${esc(x[1])}</b></div>`).join('');}catch(e){flash(e.message,true);}}
async function fitCheck(){try{const d=await api('/api/fit-check',{gguf_path:$('#gguf').value.trim(),max_context:Number($('#fitCtx').value),kv:$('#fitKvSel').value});$('#fitKv').hidden=false;$('#fitKv').innerHTML=Object.entries(d).map(([k,v])=>`<div><span>${esc(k)}</span><b>${esc(v)}</b></div>`).join('');}catch(e){flash(e.message,true);}}
function bind() { $('#tok').value=tok();$('#saveTok').onclick=()=>{localStorage.setItem('strata_tok',$('#tok').value.trim());flash('token guardado');}; document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>setTab(b.dataset.v)); $('#ovRefresh').onclick=refresh; $('#ovOptimize').onclick=()=>setTab('opt'); $('#ovParams').onclick=()=>{state.selected=state.selected||state.active;setTab('params');}; $('#lang').value=localStorage.getItem('strata_lang')||'en';$('#lang').onchange=()=>{localStorage.setItem('strata_lang',$('#lang').value);applyLang();renderModels();renderQuickHelp();};$('#prefTheme').onchange=savePreferences;$('#prefDensity').onchange=savePreferences;$('#prefMotion').onchange=savePreferences;$('#prefReasoning').onchange=savePreferences;$('#prefsReset').onclick=resetPreferences;$('#traceRefresh').onclick=loadTraces;$('#histRange').onchange=loadPerformance;$('#connRefresh').onclick=loadConnection;$('#connApply').onclick=applyConnection;$('#cfgBtn').onclick=saveParams;$('#restartBtn').onclick=async()=>{const id=state.selected||state.active;if(id){await modelAction('stop',id);await selectModel(id);}};$('#evalBtn').onclick=runEvaluation;$('#chkBtn').onclick=()=>loadUpdate(true);$('#updBtn').onclick=async()=>{try{const d=await api('/api/update',{});if(d.job_id)await waitJob(d.job_id);flash('actualización ejecutada; revisa el resultado');loadUpdate(false);}catch(e){flash(e.message,true);}};$('#tunStart').onclick=async()=>{try{const d=await api('/api/tunnel-start',{force_key:true});if(d.job_id)await waitJob(d.job_id);flash(`túnel: ${d.url||d.status}`);loadTunnel();}catch(e){flash(e.message,true);}};$('#tunStop').onclick=async()=>{try{const d=await api('/api/tunnel-stop',{});if(d.job_id)await waitJob(d.job_id);flash('túnel apagado');loadTunnel();}catch(e){flash(e.message,true);}};$('#fitBtn').onclick=fitCheck;$('#addBtn').onclick=async()=>{try{const b={gguf_path:$('#gguf').value.trim(),id:$('#nid').value.trim(),label:$('#nlabel').value.trim(),port:$('#nport').value.trim(),pack:$('#npack').value.trim(),expert_profile:$('#nprof').value.trim()};Object.keys(b).forEach(k=>{if(!b[k])delete b[k];});const d=await api('/api/add',b);flash(`modelo agregado: ${d.id}`);await refresh();}catch(e){flash(e.message,true);}};$('#clearLog').onclick=()=>$('#log').textContent='—';applyLang();applyPreferences();renderQuickHelp(); }
bind(); refresh(); setTab(location.hash.slice(1) || 'models'); window.addEventListener('hashchange',()=>setTab(location.hash.slice(1),false)); document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')refresh();}); setInterval(refresh,5000);